// @ts-check
import { defineConfig } from 'astro/config';

// Static output — generates plain HTML files, same as the original site.
// Sitemap: a single flat /sitemap.xml is generated by src/pages/sitemap.xml.ts.
// We intentionally do NOT use @astrojs/sitemap, which always emits a sitemap
// index + a nested sitemap-0.xml.
export default defineConfig({
  site: 'https://probrothers.com',
  // Keep emitted HTML close to the hand-written source (no extra minification surprises).
  build: {
    format: 'directory',
  },
  vite: {
    build: { cssMinify: true },
  },
});
